apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-platform.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  OLLAMA_HOST: {{ .Values.config.ollamaHost | quote }}
