apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-platform.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ai-platform.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
