apiVersion: v1
kind: Service
metadata:
  name: devops-ai-assistant
  labels:
    app: devops-ai-assistant
spec:
  type: NodePort
  selector:
    app: devops-ai-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
