name: devops-ai-assistant

image:
  tag: latest

service:
  port: 8000

ingress:
  path: /

persistence:
  enabled: true
  size: 1Gi
  mountPath: /app/vectordb

initIngest:
  enabled: true

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
